FROM node:22-slim as builder

RUN apt-get update && apt-get install -y procps

WORKDIR /app

COPY package*.json ./ 

RUN npm ci --ignore-scripts

COPY . .

RUN npm run build

RUN npm prune --omit-dev

FROM node:22-slim as runner

WORKDIR /app

RUN apt-get update && apt-get install -y procps wget && \
 rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/dist ./
COPY --from=builder /app/node_modules ./node_modules

COPY --from=builder  /app/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

COPY --from=builder  /app/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 3000

RUN useradd -m appuser
USER appuser

ENTRYPOINT [ "/user/local/bin/entrypoint.sh" ]
